name: Check phpcs
on:
  pull_request:
    branches: [ dev ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0.6
        extensions: mbstring, bcmath
    
    - name: Copy .env.example to .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install composer dependencies
      run: |
        composer self-update
        composer clearcache
        composer install
      
    - name: Set required directory permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Generate encryption key
      run: php artisan key:generate

    - name: PHP Code Sniffer
      run: php vendor/bin/phpcs --standard=phpcs.xml -i
