name: Laravel CI
on:
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0.6
        extensions: mbstring, bcmath
        
    - name: Install SSH Key
      # You may pin to the exact commit or the version.
      # uses: shimataro/ssh-key-action@ce5317ebbfca1b9a91612907480ba1af95d05b1d
      uses: shimataro/ssh-key-action@v2.3.0
      with:
        # SSH private key
        key:  ${{ secrets.SSH_SECRET_KEY }}
        # SSH key file name (default: id_rsa)
        # public keys of SSH servers
        known_hosts:  ${{ secrets.KNOWN_HOSTS }}
        
    - name: Copy .env.example to .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install composer dependencies
      run: composer install

    - name: Set required directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Generate encryption key
      run: php artisan key:generate

    - name: Create temporary sqlite database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run laravel database migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    - name: Install NPM dependencies
      run: npm install

    - name: Minify CSS and JS files
      run: npm run prod

    - name: Run unit tests via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/phpunit

    - name: PHP Code Sniffer
      run: php vendor/bin/phpcs --standard=phpcs.xml .
